[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sapienza-fds-pokemon"
version = "0.1.0"
description = "Pokemon Battles Prediction - Sapienza FDS Competition"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]